# Generated by Django 5.1 on 2024-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.TextField(
                blank=True,
                help_text="Введите название компании",
                null=True,
                verbose_name="Название компании",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="inn",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="ИНН"
            ),
        ),
    ]
