# Generated by Django 4.2.2 on 2024-10-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="inn",
            field=models.CharField(
                blank=True,
                help_text="Введите индивидуальный номер налогоплательщика",
                max_length=12,
                null=True,
                verbose_name="ИНН",
            ),
        ),
    ]
