# Generated by Django 5.1 on 2024-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания (записи в БД)'),
        ),
    ]
